// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	AuthorID  pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

type Post struct {
	ID          pgtype.UUID
	AuthorID    pgtype.UUID
	Slug        string
	Title       string
	ContentMd   string
	Status      string
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PostTag struct {
	PostID pgtype.UUID
	TagID  pgtype.UUID
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Tag struct {
	ID   pgtype.UUID
	Name string
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
